# lisy80 Makefile
# RTH 07.2017
# for test_pic_eeprom.c prog

CC      = /usr/bin/gcc
CFLAGS  = -Wall -g -D_REENTRANT -DDEBUG
LDFLAGS = -lwiringPi

OBJ = check_K3.o

tester: $(OBJ)
	$(CC) $(CFLAGS) -o check_K3 $(OBJ) $(LDFLAGS)

%.o: ../%.c ../%.h
	$(CC) $(CFLAGS) -c $<

