# lisy80 Makefile
# RTH 07.2017
# for getdip4andS2.c prog

CC      = /usr/bin/gcc
CFLAGS  = -Wall -g -D_REENTRANT -DDEBUG
LDFLAGS = -lwiringPi  -li2c

OBJ = lisy_check.o

getdip4andS2: $(OBJ)
	$(CC) $(CFLAGS) -o getdip4andS2 $(OBJ) $(LDFLAGS)

%.o: ../%.c ../%.h
	$(CC) $(CFLAGS) -c $<

