# lisy80 Makefile
# RTH 07.2017
# for test_pic_eeprom.c prog

CC      = /usr/bin/gcc
CFLAGS  = -Wall -g -D_REENTRANT -DDEBUG
LDFLAGS = -lwiringPi  -li2c

OBJ = lisy_check.o

tester: $(OBJ)
	$(CC) $(CFLAGS) -o lisy_check $(OBJ) $(LDFLAGS)

%.o: ../%.c ../%.h
	$(CC) $(CFLAGS) -c $<

