# lisy80 Makefile
# RTH 07.2017
# for getdip4 prog

CC      = /usr/bin/gcc
CFLAGS  = -Wall -g -D_REENTRANT -DDEBUG
LDFLAGS = -lwiringPi

OBJ = utils.o hw_lib.o switches.o displays.o coils.o eeprom.o fileio.o lisy.o getdip4andS2.o

tester: $(OBJ)
	$(CC) $(CFLAGS) -o getdip4andS2 $(OBJ) $(LDFLAGS)

%.o: ../%.c ../%.h
	$(CC) $(CFLAGS) -c $<

